- name: ec2 creation
  hosts: localhost
  become: yes
  tasks:
    - ec2:
        key_name: mykey
        instance_type: t2.micro
        image: ami-062f7200baf2fa504
        wait: yes
        group: webserver
        count: 3
        vpc_subnet_id: subnet-29e63245
        assign_public_ip: yes
        aws_access_key :
        aws_secret_key:


