- name: using loop
  hosts: all
  become: yes
  tasks:
   - name: install the software
     yum:
        name: "{{ item }}"
        state: present
     loop:
      - httpd
      - vsftpd
      - mariadb
    
